In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

#### Задание 1

In [2]:
A = np.array([[1,2,3], [4,0,6], [7,8,9]])
B = np.array([12,2,1])
np.linalg.solve(A, B)

array([-9.2       ,  0.9       ,  6.46666667])

#### Задание 2

In [3]:
eq1 = [1, 2, -1]
eq2 = [3, -4, 0]
eq3 = [8, -5, 2]
eq4 = [2, -5, 0]
eq5 = [11, 4, -7]
A = np.array([eq1, eq2, eq3, eq4, eq5])
B = np.array([1, 7, 12, 7, 15])
np.linalg.lstsq(A, B, rcond=None)

(array([ 1.15601029, -0.889718  , -0.85029782]),
 array([0.66772534]),
 3,
 array([14.89650167, 10.4695886 ,  2.73531577]))

#### Задание 3

In [4]:
A = np.array([[1,2,3], [4,5,6], [7,8,9]])
B = np.array([[12,2,1]])
np.linalg.det(A)

0.0

так как определитель матрицы A равен 0, система несовместна

In [5]:
C = np.concatenate((A, B.T), axis=1)
print(C)

[[ 1  2  3 12]
 [ 4  5  6  2]
 [ 7  8  9  1]]


In [6]:
np.linalg.matrix_rank(A), np.linalg.matrix_rank(C)

(2, 3)

так как ранк расширенной матрицы больше исходной, система не имеет решений

попробуем поменять правую часть, чтобы система стала совместной

In [7]:
B1 = np.array([[3,2,1]])
C1 = np.concatenate((A, B1.T), axis=1)

In [8]:
print(C1)
print(np.linalg.matrix_rank(C1))

[[1 2 3 3]
 [4 5 6 2]
 [7 8 9 1]]
2


In [12]:
np.linalg.lstsq(A, B1[0], rcond=None)

(array([-1.94444444, -0.11111111,  1.72222222]),
 array([], dtype=float64),
 2,
 array([1.68481034e+01, 1.06836951e+00, 4.41842475e-16]))