In [1]:
import numpy as np

#### Задание 1

In [2]:
A = np.array([[1,2,3], [4,0,6], [7,8,9]])
B = np.array([12,2,1])
np.linalg.solve(A, B)

array([-9.2       ,  0.9       ,  6.46666667])

#### Задание 2

In [3]:
eq1 = [1, 2, -1]
eq2 = [3, -4, 0]
eq3 = [8, -5, 2]
eq4 = [2, -5, 0]
eq5 = [11, 4, -7]
A = np.array([eq1, eq2, eq3, eq4, eq5])
B = np.array([1, 7, 12, 7, 15])
np.linalg.lstsq(A, B, rcond=None)

(array([ 1.15601029, -0.889718  , -0.85029782]),
 array([0.66772534]),
 3,
 array([14.89650167, 10.4695886 ,  2.73531577]))